sudo: false
language: python
addons:
  apt:
    packages:
      - npm
python:
  - "2.7"
  - "3.6"
install:
  - npm install jsdoc@3.5.5
  - pip install tox-travis
script:
  - PATH=$TRAVIS_BUILD_DIR/node_modules/.bin:$PATH tox
